import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import BigNumber from 'bignumber.js'
import { UnstakedTokens } from '../../../components/CollectionStakePool/UnstakedTokens'
import ViewSwitch from '../../../components/CollectionStakePool/ViewSwitch'
import { StakedTokens } from '../../../components/CollectionStakePool/StakedTokens'
import { useSelector } from 'react-redux'
import Web3Connect from '../../../components/Web3Connect'
import { useActiveWeb3React } from '../../../hooks'

const randomGhostIds = (count) => {
  let ids = []
  for (let i = 0; i < count; i++) {
    let uniqueId = ~~(Math.random() * 7000)
    while (ids.includes(uniqueId)) {
      uniqueId = ~~(Math.random() * 7000)
    }
    ids.push(uniqueId)
  }
  return ids
}

const StakePool = (props) => {
  const router = useRouter()
  const { id } = router.query
  const pools = useSelector((state: any) => state.stakePools.pools)
  const [poolData, setPoolData] = useState({})
  const [pane, setPane] = useState('dashboard')

  const { account } = useActiveWeb3React()
  const [userLittleGhosts, setUserLittleGhosts] = useState(randomGhostIds(24))
  const [unstakedTokens, setUnstakedTokens] = useState([])
  const [stakedTokens, setStakedTokens] = useState([])

  useEffect(() => {
    for (let pool of pools) if (pool._id === id) setPoolData(pool)
  }, [])

  useEffect(() => {
    setUnstakedTokens(userLittleGhosts.filter((id) => !stakedTokens.includes(id)))
  }, [userLittleGhosts, stakedTokens])

  const handleStakeTokens = (tokenIdsToStake) => {
    setStakedTokens(stakedTokens.concat(tokenIdsToStake))
    setUnstakedTokens(unstakedTokens.filter((id) => !tokenIdsToStake.includes(id)))
  }

  const handleUnstakeTokens = (tokenIdsToUnstake) => {
    setUnstakedTokens(unstakedTokens.concat(tokenIdsToUnstake))
    setStakedTokens(stakedTokens.filter((id) => !tokenIdsToUnstake.includes(id)))
  }

  const generateNewIds = () => {
    setUserLittleGhosts(randomGhostIds(24))
  }

  useEffect(() => {
    console.log('userLittleGhosts: ' + userLittleGhosts)
  }, [userLittleGhosts])
  useEffect(() => {
    console.log('unstakedTokens: ' + unstakedTokens)
  }, [unstakedTokens])
  useEffect(() => {
    console.log('stakedTokens: ' + stakedTokens)
  }, [stakedTokens])

  return (
    <div id="stake-pool" className="w-full">
      <Head>
        <title>{'LittleGhosts Staking UI'}</title>
        <meta name="description" content="Generated by LittleGhosts Staking UI" />
        <link rel="icon" href={props.data?.imageUrl ?? `/favicon.ico`} />
      </Head>

      <div className="relative z-0 flex flex-col gap-4 mx-10 mt-4 mb-8">
        <HeroLarge {...poolData} />

        {/* <AttributeAnalytics /> */}
        <div className="flex justify-end">
          <ViewSwitch viewMode={pane} updateViewMode={setPane} />
        </div>
        {
          {
            dashboard: (
              <div className="flex flex-col gap-4">
                {/* {!!rewardDistributorData.data &&
                  !!stakedTokenDatas.data?.length && (
                    <Info
                      colorized
                      icon="performance"
                      header="Personal Charts"
                      description="View your recent performance"
                      style={{ color: stakePoolMetadata?.colors?.fontColor }}
                      content={
                        <div className="flex items-center justify-end grow">
                          <PerformanceStats />
                        </div>
                      }
                    />
                  )} */}
                <StakePoolNotice account={account} />
                <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                  <UnstakedTokens
                    unstakedTokens={unstakedTokens}
                    handleStakeTokens={handleStakeTokens}
                    generateNewIds={generateNewIds}
                  />
                  <StakedTokens stakedTokens={stakedTokens} handleUnstakeTokens={handleUnstakeTokens} />
                </div>
              </div>
            ),
            leaderboard: null, //<StakePoolLeaderboard />,
          }[pane]
        }
      </div>

      <div id="bottom-margin" className="h-24"></div>
    </div>
  )
}

const StakePoolNotice = (props) => {
  // const { data: stakePool, isFetched: stakePoolLoaded } = useStakePoolData()
  const stakePoolMetadata = { notFound: false }
  const stakePool = null
  const stakePoolLoaded = false
  return (
    <>
      {(!stakePool && stakePoolLoaded) || stakePoolMetadata?.notFound ? (
        <div className="rounded-md border-[1px] bg-opacity-40 p-4 text-center text-lg font-semibold">
          Stake pool not found
        </div>
      ) : (
        !props.account && (
          <div className="cursor-pointer rounded-md border-[1px] text-center text-lg font-semibold border-cyan-blue bg-blue hover:bg-cyan-blue bg-opacity-40 hover:bg-opacity-40">
            <Web3Connect
              style={{
                paddingTop: '16px',
                paddingBottom: '16px',
                width: '100%',
                height: '100%',
                borderRadius: '0.375rem',
                backgroundColor: 'transparent',
              }}
              setModalOpen={false}
            />
          </div>
        )
      )}
    </>
  )
}

const HeroLarge = (props) => {
  return (
    <div className="relative flex flex-wrap items-stretch justify-center w-full gap-8 py-8 lg:flex-nowrap lg:justify-between lg:gap-24">
      <StakePoolImage imageSource={props.avatar || '/nft.png'} />
      <div className="flex w-3/4 grow-[2] flex-col pt-4">
        <div className="flex flex-col gap-6 mb-6">
          <div className="text-4xl">{props?.name ?? 'Unnamed Collection'}</div>
          <div className="text-lg text-medium-3">
            {props?.description ??
              `Stake your token(s) to earn rewards from various reward mechanisms including tokens, merchandise, redeemable rewards by the ${
                props?.name ?? 'Collection'
              } pool.`}
          </div>
          {/* <StakePoolConfig /> */}
        </div>
        <HeroStats {...props} />
      </div>
    </div>
  )
}

const HeroStats = (props) => {
  const rewardDistributorData = {
    data: {
      parsed: {
        maxRewardSecondsReceived: new BigNumber(0),
      },
    },
  }
  const stakePoolEntries = { data: [] }
  const maxStaked = ~~(Math.random() * 10000)
  const totalStaked = {
    isFetched: true,
    data: ~~(Math.random() * maxStaked),
  }
  const stakePoolMetadata = {
    data: {},
    maxStaked: maxStaked,
  }

  return (
    <div className="flex flex-col flex-wrap w-full px-12 py-6 text-gray-200 border-2 border-gray-600 bg-dark-800 gap-y-5 rounded-xl md:flex-row justify-evenly bg-opacity-5">
      <div className="flex flex-col items-center justify-center flex-1">
        <div className="text-lg text-[#6d6c7c]">Total Staked</div>
        {!(props.totalStaked >= 0) ? (
          <div className="w-10 h-6 rounded-md animate-pulse bg-dark-700"></div>
        ) : (
          <div className="text-xl text-center text-light-1">
            {props.totalStaked?.toLocaleString()} {props.totalSupply ? `/ ${props.totalSupply.toLocaleString()}` : ''}
          </div>
        )}
      </div>
      {props.totalStaked >= 0 && props.totalSupply >= 0 && (
        <>
          <div className="mx-6 my-auto hidden h-10 w-[1px] bg-gray-600 md:flex"></div>
          <div className="flex flex-col items-center justify-center flex-1">
            <p className="text-lg text-[#6d6c7c]">Percent Staked</p>
            {!(props.totalStaked >= 0) ? (
              <div className="w-10 h-6 rounded-md animate-pulse bg-dark-700"></div>
            ) : (
              <div className="text-xl text-center text-light-1">
                {
                  /* {stakePoolEntries.data?.length && */
                  props.totalStaked &&
                    // Math.floor(((stakePoolEntries.data?.length * 100) / (maxStaked ?? 0)) * 10000) / 10000}
                    Math.floor(((props.totalStaked * 100) / (props.totalSupply ?? 0)) * 10000) / 10000
                }
                %
              </div>
            )}
          </div>
        </>
      )}
      {rewardDistributorData.data && (
        <>
          <div className="mx-6 my-auto hidden h-10 w-[1px] bg-gray-600 md:flex"></div>
          <div className="flex flex-col items-center justify-center flex-1">
            <p className="text-lg text-[#6d6c7c]">
              {rewardDistributorData.data.parsed?.maxRewardSecondsReceived?.eq(new BigNumber(1))
                ? '1x Claim'
                : 'Rewards Rate'}
            </p>
            <RewardsRate />
          </div>
          <div className="mx-6 my-auto hidden h-10 w-[1px] bg-gray-600 md:flex"></div>
          <div className="flex flex-col items-center justify-center flex-1">
            <p className="text-lg text-[#6d6c7c]">Treasury Balance</p>
            <TreasuryBalance className="text-xl text-center text-light-1" />
          </div>
        </>
      )}
    </div>
  )
}

const TreasuryBalance = (props) => {
  const rewardsRate = { data: {} }
  const rewardDistributorData = { data: {} }
  const rewardMintInfo = { data: {} }
  const stakePoolMetadata = { data: {} }
  const rewardDistributorTokenAccountData = { isFetched: false }
  const balance = Math.random() * 1000

  const isZeroBalance = (balance) => {
    return new BigNumber(0).isEqualTo(balance)
  }

  return (
    <>
      {!rewardsRate.data ||
      !rewardMintInfo.data ||
      !rewardDistributorData.data ||
      !rewardDistributorTokenAccountData.isFetched ? (
        <div className="w-10 h-6 rounded-md animate-pulse bg-dark-700"></div>
      ) : (
        <div style={{ color: isZeroBalance(balance) ? '#f87171' : 'white' }}>{Math.random() * 10}</div>
      )}
    </>
  )
}

const RewardsRate = (props) => {
  const rewardsRate = null
  const rewardDistributorData = null
  const rewardMintInfo = null
  // const environment = null
  // const stakePoolMetadata = null

  return (
    <>
      {!rewardsRate?.data || !rewardMintInfo?.data || !rewardDistributorData?.data ? (
        <div className="w-10 h-6 rounded-md animate-pulse bg-dark-700" />
      ) : (
        <div className="text-xl text-center text-light-1">
          {/* {formatAmountAsDecimal(
            rewardMintInfo.data.mintInfo.decimals,
            baseDailyRate(rewardDistributorData.data),
            Math.min(rewardMintInfo.data.mintInfo.decimals, 3)
          )} */}{' '}
          {/* <a
            className="underline"
            style={{
              color: stakePoolMetadata?.colors?.fontColor
                ? stakePoolMetadata?.colors?.fontColor
                : 'white',
            }}
            target="_blank"
            href={pubKeyUrl(
              rewardDistributorData.data.parsed?.rewardMint,
              environment.label
            )}
            rel="noreferrer"
          >
            {rewardMintInfo.data.tokenListData?.symbol ||
              rewardMintInfo.data.metaplexMintData?.data.symbol ||
              '???'}
          </a> */}{' '}
          {rewardDistributorData.data.parsed?.maxRewardSecondsReceived?.eq(new BigNumber(1)) ? '' : '/ Day'}
        </div>
      )}
    </>
  )
}

const StakePoolImage = (props) => {
  return (
    <div className="relative flex items-center justify-center w-1/4 grow rounded-xl">
      <img className="max-h-[200px] w-auto rounded-xl" src={props.imageSource} alt={'Stake pool image'} />
    </div>
  )
}

export default StakePool
